In [4]:
import pandas as pd
import numpy as np
from itertools import product
import seaborn as sns
import os
import matplotlib.pyplot as plt
import scipy.sparse 
import sklearn

%matplotlib inline
data_path = 'data'

In [5]:
for p in [np, pd, scipy, sklearn]:
  print(p.__name__, p.__version__)

numpy 1.21.6
pandas 1.3.5
scipy 1.7.3
sklearn 1.0.2

In [6]:
sales = pd.read_csv(os.path.join(data_path, 'sales_train.csv'))
items = pd.read_csv(os.path.join(data_path, 'items.csv'))
item_categories = pd.read_csv(os.path.join(data_path, 'item_categories.csv'))
test = pd.read_csv(os.path.join(data_path, 'test.csv'))
shops = pd.read_csv(os.path.join(data_path, 'shops.csv'))

In [7]:
sales.item_cnt_day.describe()

count    2.935849e+06
mean     1.242641e+00
std      2.618834e+00
min     -2.200000e+01
25%      1.000000e+00
50%      1.000000e+00
75%      1.000000e+00
max      2.169000e+03
Name: item_cnt_day, dtype: float64

In [8]:
sales.loc[sales.item_cnt_day >1000]

,date,date_block_num,shop_id,item_id,item_price,item_cnt_day
2909818,28.10.2015,33,12,11373,0.908714,2169.0

In [9]:
sales = sales.loc[sales.item_cnt_day <=1000]

In [10]:
sales.item_cnt_day.describe()

count    2.935848e+06
mean     1.241903e+00
std      2.292962e+00
min     -2.200000e+01
25%      1.000000e+00
50%      1.000000e+00
75%      1.000000e+00
max      1.000000e+03
Name: item_cnt_day, dtype: float64

In [11]:
sales.item_price.describe()

count    2.935848e+06
mean     8.908535e+02
std      1.729800e+03
min     -1.000000e+00
25%      2.490000e+02
50%      3.990000e+02
75%      9.990000e+02
max      3.079800e+05
Name: item_price, dtype: float64

In [12]:
sales.loc[sales.item_price > 100000]

,date,date_block_num,shop_id,item_id,item_price,item_cnt_day
1163158,13.12.2013,11,12,6066,307980.0,1.0

In [13]:
sales = sales.loc[sales.item_price <=100000]

In [14]:
sales.item_price.describe()

count    2.935847e+06
mean     8.907489e+02
std      1.720490e+03
min     -1.000000e+00
25%      2.490000e+02
50%      3.990000e+02
75%      9.990000e+02
max      5.920000e+04
Name: item_price, dtype: float64

In [15]:
(sales.date_block_num.unique())

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33])

In [16]:
a=[1,2,3]
b=[4,5,6]
c=[0]
d=[]
d.append(np.array(list(product(a,b,c))))
d.append(np.array(list(product(a,b,c))))
print(d)
print(np.vstack(d))
print(np.concatenate(d,axis=0))
print(np.stack(d,axis=0))

[array([[1, 4, 0],
       [1, 5, 0],
       [1, 6, 0],
       [2, 4, 0],
       [2, 5, 0],
       [2, 6, 0],
       [3, 4, 0],
       [3, 5, 0],
       [3, 6, 0]]), array([[1, 4, 0],
       [1, 5, 0],
       [1, 6, 0],
       [2, 4, 0],
       [2, 5, 0],
       [2, 6, 0],
       [3, 4, 0],
       [3, 5, 0],
       [3, 6, 0]])]
[[1 4 0]
 [1 5 0]
 [1 6 0]
 [2 4 0]
 [2 5 0]
 [2 6 0]
 [3 4 0]
 [3 5 0]
 [3 6 0]
 [1 4 0]
 [1 5 0]
 [1 6 0]
 [2 4 0]
 [2 5 0]
 [2 6 0]
 [3 4 0]
 [3 5 0]
 [3 6 0]]
[[1 4 0]
 [1 5 0]
 [1 6 0]
 [2 4 0]
 [2 5 0]
 [2 6 0]
 [3 4 0]
 [3 5 0]
 [3 6 0]
 [1 4 0]
 [1 5 0]
 [1 6 0]
 [2 4 0]
 [2 5 0]
 [2 6 0]
 [3 4 0]
 [3 5 0]
 [3 6 0]]
[[[1 4 0]
  [1 5 0]
  [1 6 0]
  [2 4 0]
  [2 5 0]
  [2 6 0]
  [3 4 0]
  [3 5 0]
  [3 6 0]]

 [[1 4 0]
  [1 5 0]
  [1 6 0]
  [2 4 0]
  [2 5 0]
  [2 6 0]
  [3 4 0]
  [3 5 0]
  [3 6 0]]]

In [17]:
(sales.loc[sales.date_block_num==0, 'shop_id'].unique())

array([59, 25, 24, 23, 19, 22, 18, 21, 28, 27, 29, 26,  4,  6,  2,  3,  7,
        0,  1, 16, 15,  8, 10, 14, 13, 12, 53, 31, 30, 32, 35, 56, 54, 47,
       50, 42, 43, 52, 51, 41, 38, 44, 37, 46, 45])

In [18]:
sales.loc[sales.date_block_num==0, 'item_id'].unique()

array([22154,  2552,  2554, ...,   628,   631,   621])

In [19]:
a=np.array([1,2,3])
b=np.array([4,5,6])
a,b=3,4
a= [np.array([1,2,3]),np.array([1,2,3])]
print(np.vstack(a))
#print(np.stack([a,b],axis=0))

[[1 2 3]
 [1 2 3]]

In [20]:
grid = []
cols = ['shop_id', 'item_id', 'date_block_num']

for month in range(34):
  curr_items = sales.loc[sales.date_block_num==month, 'item_id'].unique()
  curr_shops = sales.loc[sales.date_block_num==month, 'shop_id'].unique()
  grid.append(np.array(list(product(curr_items, curr_shops, [month])), dtype= np.int32))
grid = pd.DataFrame(np.concatenate(grid,axis=0), columns=cols,dtype = np.int32)

In [21]:
grid

          shop_id  item_id  date_block_num
0           22154       59               0
1           22154       25               0
2           22154       24               0
3           22154       23               0
4           22154       19               0
...           ...      ...             ...
10913799     7440       28              33
10913800     7440       26              33
10913801     7440       25              33
10913802     7440       24              33
10913803     7440       21              33

[10913804 rows x 3 columns]

In [22]:
gb = sales.groupby(cols, as_index=False).sum().drop(['item_price'],axis=1)

In [23]:
gb.head()

   shop_id  item_id  date_block_num  item_cnt_day
0        0       30               1          31.0
1        0       31               1          11.0
2        0       32               0           6.0
3        0       32               1          10.0
4        0       33               0           3.0

In [24]:
gb = gb.rename(columns={'item_cnt_day': 'target'})

In [25]:
gb.head()

   shop_id  item_id  date_block_num  target
0        0       30               1    31.0
1        0       31               1    11.0
2        0       32               0     6.0
3        0       32               1    10.0
4        0       33               0     3.0

In [26]:
gb

         shop_id  item_id  date_block_num  target
0              0       30               1    31.0
1              0       31               1    11.0
2              0       32               0     6.0
3              0       32               1    10.0
4              0       33               0     3.0
...          ...      ...             ...     ...
1609118       59    22164              27     2.0
1609119       59    22164              30     1.0
1609120       59    22167               9     1.0
1609121       59    22167              11     2.0
1609122       59    22167              17     1.0

[1609123 rows x 4 columns]

In [27]:
grid

          shop_id  item_id  date_block_num
0           22154       59               0
1           22154       25               0
2           22154       24               0
3           22154       23               0
4           22154       19               0
...           ...      ...             ...
10913799     7440       28              33
10913800     7440       26              33
10913801     7440       25              33
10913802     7440       24              33
10913803     7440       21              33

[10913804 rows x 3 columns]

In [28]:
all_data = grid.merge(gb, how='left',on=cols).fillna(0)

In [29]:
all_data

          shop_id  item_id  date_block_num  target
0           22154       59               0     0.0
1           22154       25               0     0.0
2           22154       24               0     0.0
3           22154       23               0     0.0
4           22154       19               0     0.0
...           ...      ...             ...     ...
10913799     7440       28              33     0.0
10913800     7440       26              33     0.0
10913801     7440       25              33     0.0
10913802     7440       24              33     0.0
10913803     7440       21              33     0.0

[10913804 rows x 4 columns]

In [30]:
all_data = all_data.merge(items, on=['item_id'], how='left')

In [31]:
all_data

,shop_id,item_id,date_block_num,target,item_name,item_category_id
0,22154,59,0,0.0,100 шедевров классики (mp3-CD) (Digipack),57
1,22154,25,0,0.0,/ТЫ - ТРУП,40
2,22154,24,0,0.0,/СМЕРТЕЛЬНЫЙ РАСКЛАД,40
3,22154,23,0,0.0,/СЕВЕР И ЮГ /Ч.2/,40
4,22154,19,0,0.0,/ЗОЛОТАЯ КОЛЛЕКЦИЯ м/ф-72,40
...,...,...,...,...,...,...
10913799,7440,28,33,0.0,"007 Legends [PС, Jewel, русская версия]",30
10913800,7440,26,33,0.0,/УМНОЖАЮЩИЙ ПЕЧАЛЬ т.2 (сер.3-4),40
10913801,7440,25,33,0.0,/ТЫ - ТРУП,40
10913802,7440,24,33,0.0,/СМЕРТЕЛЬНЫЙ РАСКЛАД,40
10913803,7440,21,33,0.0,/ПОСЛЕДНИЙ ШАНС,40

In [32]:
gb1 = sales.drop(['item_id', 'item_price'],axis=1).groupby(['shop_id', 'date_block_num'],as_index=False).sum()
gb1 = gb1.rename(columns={'item_cnt_day':'shop_block_target_sum'})
gb2 = sales.drop(['item_id', 'item_price'],axis=1).groupby(['shop_id', 'date_block_num'],as_index=False).mean()
gb2 = gb2.rename(columns={'item_cnt_day': 'shop_block_target_mean'})

In [33]:
gb = gb1.merge(gb2, how='left',on=['shop_id','date_block_num'])
gb

      shop_id  date_block_num  shop_block_target_sum  shop_block_target_mean
0           0               0                 5578.0                1.163781
1           0               1                 6127.0                1.209913
2           1               0                 2947.0                1.093912
3           1               1                 3364.0                1.127346
4           2               0                 1146.0                1.070028
...       ...             ...                    ...                     ...
1581       59              29                  913.0                1.092105
1582       59              30                  992.0                1.082969
1583       59              31                 1214.0                1.247688
1584       59              32                  914.0                1.174807
1585       59              33                  790.0                1.083676

[1586 rows x 4 columns]

In [34]:
all_data = all_data.merge(gb,how='left',on=['shop_id','date_block_num']).fillna(0)

In [35]:
gb1 = sales.drop(['shop_id', 'item_price'],axis=1).groupby(['item_id', 'date_block_num'],as_index=False).sum()
gb1 = gb1.rename(columns={'item_cnt_day':'item_block_target_sum'})
gb2 = sales.drop(['shop_id', 'item_price'],axis=1).groupby(['item_id', 'date_block_num'],as_index=False).mean()
gb2 = gb2.rename(columns={'item_cnt_day': 'item_block_target_mean'})

In [36]:
gb = gb1.merge(gb2, how='left',on=['item_id','date_block_num'])
gb

        item_id  date_block_num  item_block_target_sum  item_block_target_mean
0             0              20                    1.0                     1.0
1             1              15                    2.0                     1.0
2             1              18                    1.0                     1.0
3             1              19                    1.0                     1.0
4             1              20                    1.0                     1.0
...         ...             ...                    ...                     ...
233906    22168               0                    2.0                     1.0
233907    22168               1                    2.0                     1.0
233908    22168               2                    1.0                     1.0
233909    22168               8                    1.0                     1.0
233910    22169              14                    1.0                     1.0

[233911 rows x 4 columns]

In [37]:
all_data = all_data.merge(gb,on=['item_id','date_block_num'],how='left').fillna(0)

In [38]:
sales_with_categories = sales.merge(items,on=['item_id'],how='left')
gb1 = sales_with_categories.drop(['shop_id', 'item_price','item_id'],axis=1).groupby(['item_category_id', 'date_block_num'],as_index=False).sum()
gb1 = gb1.rename(columns={'item_cnt_day':'item_cat_block_target_sum'})
gb2 = sales_with_categories.drop(['shop_id', 'item_price','item_id'],axis=1).groupby(['item_category_id', 'date_block_num'],as_index=False).mean()
gb2 = gb2.rename(columns={'item_cnt_day': 'item_cat_block_target_mean'})

In [39]:
gb = gb1.merge(gb2,on=['item_category_id','date_block_num'],how='left')
gb

,item_category_id,date_block_num,item_cat_block_target_sum,item_cat_block_target_mean
0,0,0,1.0,1.000000
1,0,1,1.0,1.000000
2,0,3,1.0,1.000000
3,1,0,1.0,1.000000
4,1,1,1.0,1.000000
...,...,...,...,...
2072,83,29,258.0,1.402174
2073,83,30,298.0,1.460784
2074,83,31,293.0,1.494898
2075,83,32,277.0,1.398990
2076,83,33,348.0,1.487179

In [40]:
all_data = all_data.merge(gb, on=['item_category_id','date_block_num'],how='left').fillna(0)

In [41]:
#all_data = downcast_dtypes(all_data)
del grid,gb,gb1,gb2, sales_with_categories

In [42]:
index_cols = ['shop_id', 'item_id', 'date_block_num','item_category_id']
cols_to_rename = list(all_data.columns.difference(index_cols))
for i in ['item_name']:
    cols_to_rename.remove(i)
print(cols_to_rename)
cols_gb_item = [i for i in cols_to_rename if 'item_block' in i]
cols_gb_shop = [i for i in cols_to_rename if 'shop_block' in i]
cols_gb_cat = [i for i in cols_to_rename if 'item_cat' in i]
cols_gb_all = ['target']
cols_gb_key=[['item_id'],['shop_id'],['item_category_id'],['shop_id','item_id']]
cols_gb_value = [cols_gb_item,cols_gb_shop,cols_gb_cat,cols_gb_all]
print(cols_gb_value)

['item_block_target_mean', 'item_block_target_sum', 'item_cat_block_target_mean', 'item_cat_block_target_sum', 'shop_block_target_mean', 'shop_block_target_sum', 'target']
[['item_block_target_mean', 'item_block_target_sum'], ['shop_block_target_mean', 'shop_block_target_sum'], ['item_cat_block_target_mean', 'item_cat_block_target_sum'], ['target']]

In [43]:
del item_categories,items,sales,shops,test

In [44]:
shift_range = [1,2,3]
i=1
for month_shift in shift_range:
    for k,v in zip(cols_gb_key,cols_gb_value): 
        index_col = ['date_block_num'] + k
        train_shift = all_data[index_col + v].copy().drop_duplicates()

        train_shift['date_block_num'] = train_shift['date_block_num'] + month_shift

        foo = lambda x: '{}_lag_{}'.format(x, month_shift) if x in v else x
        train_shift = train_shift.rename(columns=foo)
        all_data = pd.merge(all_data, train_shift, on=index_col, how='left').fillna(0)
        print(i)
        i+=1

1
2
3
4
5
6
7
8
9
10
11
12

In [45]:
all_data.columns

Index(['shop_id', 'item_id', 'date_block_num', 'target', 'item_name',
       'item_category_id', 'shop_block_target_sum', 'shop_block_target_mean',
       'item_block_target_sum', 'item_block_target_mean',
       'item_cat_block_target_sum', 'item_cat_block_target_mean',
       'item_block_target_mean_lag_1', 'item_block_target_sum_lag_1',
       'shop_block_target_mean_lag_1', 'shop_block_target_sum_lag_1',
       'item_cat_block_target_mean_lag_1', 'item_cat_block_target_sum_lag_1',
       'target_lag_1', 'item_block_target_mean_lag_2',
       'item_block_target_sum_lag_2', 'shop_block_target_mean_lag_2',
       'shop_block_target_sum_lag_2', 'item_cat_block_target_mean_lag_2',
       'item_cat_block_target_sum_lag_2', 'target_lag_2',
       'item_block_target_mean_lag_3', 'item_block_target_sum_lag_3',
       'shop_block_target_mean_lag_3', 'shop_block_target_sum_lag_3',
       'item_cat_block_target_mean_lag_3', 'item_cat_block_target_sum_lag_3',
       'target_lag_3'],
      dtype='object')

In [46]:
all_data = all_data[all_data['date_block_num'] >= 3]

In [47]:
all_data.shape

(9791009, 33)

In [48]:
all_data['December'] = all_data.date_block_num.apply(lambda x: 1 if x in [11,23] else 0)

In [49]:
all_data['Newyear_Xmas'] = all_data.date_block_num.apply(lambda x: 1 if x in [12,24] else 0)
all_data['Valentine_MenDay'] = all_data.date_block_num.apply(lambda x: 1 if x in [13,25] else 0)
all_data['WomenDay'] = all_data.date_block_num.apply(lambda x: 1 if x in [14,26] else 0)
all_data['Easter_Labor'] = all_data.date_block_num.apply(lambda x: 1 if x in [15,27] else 0)

In [50]:
data_path

'data'

In [51]:
all_data.to_pickle('data/new_sales_lag_after3.pickle')

In [52]:
all_data.head()

,shop_id,item_id,date_block_num,target,item_name,item_category_id,shop_block_target_sum,shop_block_target_mean,item_block_target_sum,item_block_target_mean,...,shop_block_target_mean_lag_3,shop_block_target_sum_lag_3,item_cat_block_target_mean_lag_3,item_cat_block_target_sum_lag_3,target_lag_3,December,Newyear_Xmas,Valentine_MenDay,WomenDay,Easter_Labor
1122795,8092,25,3,0.0,/ТЫ - ТРУП,40,0.0,0.0,0.0,0.0,...,0.0,0.0,1.145902,33489.0,0.0,0,0,0,0,0
1122796,8092,21,3,0.0,/ПОСЛЕДНИЙ ШАНС,40,0.0,0.0,0.0,0.0,...,0.0,0.0,1.145902,33489.0,0.0,0,0,0,0,0
1122797,8092,23,3,0.0,/СЕВЕР И ЮГ /Ч.2/,40,0.0,0.0,0.0,0.0,...,0.0,0.0,1.145902,33489.0,0.0,0,0,0,0,0
1122798,8092,22,3,0.0,/ПРОКЛЯТЬЕ ЭЛЬ ЧАРРО,40,0.0,0.0,0.0,0.0,...,0.0,0.0,1.145902,33489.0,0.0,0,0,0,0,0
1122799,8092,24,3,0.0,/СМЕРТЕЛЬНЫЙ РАСКЛАД,40,0.0,0.0,0.0,0.0,...,0.0,0.0,1.145902,33489.0,0.0,0,0,0,0,0

In [53]:
all_data.shape

(9791009, 38)

In [54]:
all_data.to_csv('data/new_sales_lag_after3.csv')